### ISSUE TITLE
apps/collections/contributors: Track all 70+ `ansible 2.10` collections

### ISSUE THREAD

**Issue by gundalow** [ansible-community/stats-collections#16]
Currently, https://stats.eng.ansible.com/apps/collections/contributors/ is tracking 41 collections however, https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible.in shows there are 72 (inc infoblox).

It would be good to track all of these.

**Comment by GregSutcliffe** [comment]
@gundalow is there anything stopping them being added to https://github.com/ansible-community/stats-collections/blob/main/crawler-config/collections_list.csv ? Or is it just a case of someone getting on with it?

Longer term we might want to think of something more automatic, but for now having a check on the process is probably a good thing.

**Comment by gundalow** [comment]
Just needs doing

Longer term, watching https://github.com/ansible-collections/* would be good (and treating all as new_collections), not sure if we have a way to alert, notify if things get added (and therefor need the file mapping to ansible/ansible adding in)

**Comment by GregSutcliffe** [comment]
I think a cronjob that alerts us to new collections is probably the right start point, and if all is well for a while, we could let it handle adding in the collections in some automatic way.

**Comment by GregSutcliffe** [comment]
I believe @dmsimard's PR to stats-crawler has relieved much of this. Further PRs / improvements can be added there.
