### ISSUE TITLE
Where to store the list of collections?

### ISSUE THREAD

**Issue by GregSutcliffe** [ansible-community/stats-collections#4]
We already have apps like https://stats.eng.ansible.com/apps/collections/contributors/ which consume a list of collections. This app will also need such a list.

Right now, that list is internal to Red Hat, which is not ideal. Where should it live?

I will likely create a second repo to put the GitHub crawler in (based on excellent work from @sivel) - perhaps that is the right place ... or a dedicated "stats-config" repo?

**Comment by sivel** [comment]
How do you want to limit that list?  Right now I have a script that fetches all current versions of collections from galaxy and stores their info in mongo.  I have an API built on top of that database as well, for listing all of those collections.

https://gist.github.com/sivel/a7e0e2612d255098c4abd21f07fa3c51

**Comment by GregSutcliffe** [comment]
That's probably a much longer list that we're currently consuming - I'll check it out and compare, thanks!

My assumption is that this will end up being hand-crafted, at least for now. While the stats around a given collection's mere times etc could consume that (most likely anyway, I haven't lookedt yet :P), the code for the Contributors app needs a regex of some kind to match where the code came from in ansible/ansible (so that it can calculate the historical number of contributors there). 

Admittedly, that's got a half-life - by next year we'll probably be done tracking how the migration to collections went anyway. Until then, I don't think Galaxy can tell us that information, which means we'd need to store it somewhere ... and we're back where we started :)

@gundalow thoughts?

**Comment by gundalow** [comment]
I'm OK with a hardcoded list

**Comment by GregSutcliffe** [comment]
#9 is the first cut of this.

**Comment by GregSutcliffe** [comment]
Closing for now, we can revist if it become tedious to maintain the list.
